let traces=[],examples=[];let timer=null,time=2400,currentTask='';
const $=id=>document.getElementById(id);
const words=t=>t.trim().match(/[A-Za-z']+/g)||[];
async function init(){traces=await fetch('data/traces.json').then(r=>r.json());examples=await fetch('data/examples.json').then(r=>r.json());nav();teacher();exam();traceUI();examplesUI();dashboard();}
function nav(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>show(b.dataset.page));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));}
function show(id){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.page===id));if(id==='dashboard')dashboard();}
function teacher(){$('aiCorrect').onclick=()=>ai($('aiText').value,$('aiTask').value,'aiResult');}
function exam(){$('newTrace').onclick=()=>{let t=traces[Math.floor(Math.random()*traces.length)];currentTask=t.task;$('examTrace').innerHTML=`<b>${t.title}</b><p>${t.task}</p>`;$('examText').value='';$('wordCount').textContent='0';resetTimer();startTimer();};$('examText').oninput=()=>$('wordCount').textContent=words($('examText').value).length;$('examAI').onclick=()=>ai($('examText').value,currentTask||'A2 informal email','examResult');}
function resetTimer(){if(timer)clearInterval(timer);time=2400;tick();}function startTimer(){timer=setInterval(()=>{time=Math.max(0,time-1);tick();if(time===0)clearInterval(timer)},1000)}function tick(){let m=Math.floor(time/60),s=time%60;$('timer').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function traceUI(){renderTraces('');$('traceSearch').oninput=e=>renderTraces(e.target.value.toLowerCase());}
function renderTraces(q){$('traceList').innerHTML=traces.filter(t=>(t.title+t.task+t.category).toLowerCase().includes(q)).map(t=>`<div class="box"><b>${t.title}</b><p>${t.task}</p></div>`).join('')}
function examplesUI(){renderExamples('');$('exampleSearch').oninput=e=>renderExamples(e.target.value.toLowerCase());}
function renderExamples(q){$('exampleList').innerHTML=examples.filter(e=>(e.title+e.category+e.score).toLowerCase().includes(q)).map(e=>`<div class="emailcard"><span class="scorebadge">${e.label}</span><h3>${e.title}</h3><div class="emailtext">${e.email}</div><button class="secondary" onclick="navigator.clipboard.writeText(\`${e.email.replaceAll('`','')}\`)">Copia</button></div>`).join('')}
async function ai(text,task,target){if(!text.trim()){ $(target).innerHTML='<div class="issue warn">Scrivi prima una email.</div>'; return;}$(target).innerHTML='<div class="aiout warn">🤖 Sto correggendo... provo prima Gemini 3 Flash Preview e poi gli altri modelli disponibili.</div>';try{let res=await fetch('/api/correct',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,task})});let data=await res.json();if(!res.ok)throw new Error(data.error||'Errore AI');$(target).innerHTML=`<div class="aiout"><h3>🤖 Teacher AI Report</h3>${String(data.feedback).replaceAll('\n','<br>')}</div>`;save(data.feedback);}catch(e){$(target).innerHTML=`<div class="issue bad"><b>AI non disponibile.</b><br>${e.message}<br>Controlla GEMINI_API_KEY su Vercel e fai Redeploy.</div>`}}
function save(feedback){let old=JSON.parse(localStorage.getItem('a2_fix_memory')||'[]');old.push({id:Date.now(),date:new Date().toLocaleString(),feedback:String(feedback).slice(0,500)});localStorage.setItem('a2_fix_memory',JSON.stringify(old));}
function dashboard(){let mem=JSON.parse(localStorage.getItem('a2_fix_memory')||'[]');$('dashboardBox').innerHTML=`<div class="stats"><div class="stat"><span>Correzioni AI</span><b>${mem.length}</b></div><div class="stat"><span>Ultima</span><b>${mem.length?'OK':'-'}</b></div><div class="stat"><span>Memoria</span><b>ON</b></div></div><h3>Storico AI</h3>${mem.slice().reverse().map(x=>`<div class="issue"><b>${x.date}</b><br>${x.feedback}</div>`).join('')||'<p>Nessuna correzione salvata.</p>'}`;$('clearData').onclick=()=>{localStorage.removeItem('a2_fix_memory');dashboard();}}
init();